---
$schema: "http://json-schema.org/draft-07/schema#"

name: AWS sigv4 auth schema
desc: jsonschema for AWS sigv4 auth

properties:
    aws:
        type: object
        properties:
            profile:
                type: string
            service:
                type: string
            region:
                type: string
