---
name: AWS sigv4 auth schemas
desc: pykwalify schemas for 'aws' plugin block

properties:
    aws:
        type: object
        properties:
            profile:
                type: str
            service:
                type: str
